### ISSUE TITLE
[help wanted] Error with device enrollment

### ISSUE THREAD

**Issue by Rturoz** [CanonicalLtd/iot-agent#7]
I'm following the canonical whitepaper ["Secure IoT Device Management"](https://ubuntu.com/engage/iot-device-management-whitepaper "Download") to remotely control a raspberry with Ubuntu Core 20.04.3. 

Following the whitepaper i deployed the following services:

- [IoT Identity Service](https://github.com/canonical/iot-identity "read")
- [IoT Management Service](https://github.com/canonical/iot-management "read")
- [IoT Device Twin Service](https://github.com/canonical/iot-devicetwin "read")
- MQTT broker

Later I installed the snap "iot-agent" (version 0.4) on the raspberry with Ubuntu Core 20, but during the enrollment of the device the following error appears in the log files:
**iot-agent.mqtt[1304]: 2022/01/25 21:05:26 Error with enrollment: (EnrollDevice) assertion model: type of snap "snapd" must be one of app|base|gadget|kernel|core** 

How can i fix this error?

**Comment by bugraaydogar** [comment]
Hi @Rturoz,

The issue sounds very familiar to me. I assume you are using the kubernetes yaml scripts that are available in the [iot-deploy](https://github.com/canonical/iot-deploy) repository. 

I'm afraid these images(sonicblue/*) referred in the kubernetes.yaml files are outdated and only valid for UC18. 
Therefore, I would highly suggest building your own docker images which will use the latest code from the snapd and then the mentioned issue would probably be gone.

The problem is golang is a compiled language and iot-identity and iot-agent microservices are inheriting the available functionality from the snapd.  Therefore, they need to be built within the same code base. In your case - considering you are using the pre-built images that are part of the iot-deploy scripts -, iot-identify is using an old code base whereas your iot-agent is built based on the newest snapd sources.

Let me know if my suggestion would work for you.

**Comment by Rturoz** [comment]
Hi @bugraaydogar,

thank you very much for the answer. I wanted to ask you how I can build the new docker images (starting from the ones available in the [iot-deploy](https://github.com/canonical/iot-deploy) repository) because I don't know where to start.
