### ISSUE TITLE
Run iot-agent on Ubunut  Core device

### ISSUE THREAD

**Issue by jdbelo** [CanonicalLtd/iot-agent#9]
Hi everyone 👋 ,

Does anyone has already tried to run the iot-agent span on a ubuntu-core 20 device? Did it work?
I have been trying to do it but I haven't been successful yet. In a nutshell, I created the snap from this repo (executing snapcraft command), copied this snap to the device, and installed it in --dangerous mode. Once installed, I registered the device in the iot-management service, and then I connected the snapd-control and set the agent's url. Looking into the iot-agent logs I found the following error message "Error with enrollment: (Enroll Device) assertion model: type of snap “snapd” must be one of app|base|gadget|kernel|core". Does this message sound familiar to anyone?
In the meantime, I have already reproduced this procedure on a ubuntu 20 device without any problem 😕. 

Thanks

**Comment by jdbelo** [comment]
Just a quick update, I have also attempted to connect the iot-agent to the iot-management-service on a ubuntu 18 device and on a ubuntu-core 18 device ("base": "core18") and it worked without any problem. It looks the problem only occurs on ubuntu-core 20 ("base": "core20").

Any idea about why this happening?

Thanks

**Comment by bugraaydogar** [comment]
Hi @jdbelo ,

The problem you are experiencing is completely about the iot-identity. As you might know, golang is a compiled language and iot-identity is leveraging a good amount of snapd code base and therefore, it needs to be re-compiled to be compatible with the latest snapd improvements.  Probably, you are using a old docker image, please rebuild iot-identity docker image and try again. This also explains why UC18 works but not UC20.

Good luck,
Bugra

**Comment by jdbelo** [comment]
Thanks @bugraaydogar. 

To be honest, I didn't compile any of the canonical repositories (neither iot-management, nor iot-identity, nor iot-devicetwin). I followed the instructions available on iot-deploy repository to get everything running on a VM. 

I only rebuild iot-agent snap because I realized the snapd-control plug didn't exist in the iot-agent snap available in the Global Store.

I also noticed that iot-deploy repository hasn't been recently updated, which means that some of the latest commits made in the different repositories weren't applied to it.

Do you know if there is a quick and easy way to recompile all the repositories inside the iot-deploy repository? If not, do you know how to compile all the projects individually and integrate them in iot-deploy?

Thanks

**Comment by bugraaydogar** [comment]
Hi @jdbelo ,

> I also noticed that iot-deploy repository hasn't been recently updated, which means that some of the latest commits made in the different repositories weren't applied to it.

That's correct. It is mainly because this is a reference implementation, not an official product.

> Do you know if there is a quick and easy way to recompile all the repositories inside the iot-deploy repository? If not, do you know how to compile all the projects individually and integrate them in iot-deploy?

Each repositories have the Dockerfile and it should be possible to build them by running "docker build ." After the images are built, you need to have a container repository(e.g. Docker Hub) where you could push the docker images. Finally, you need to check the all .yaml files under https://github.com/canonical/iot-deploy/tree/master/kubernetes and look for `image` keyword to replace with your own docker repository. (It should be sufficient to change the yaml files references to the `sonicblue` as part of the `image` keyword)

**Comment by jdbelo** [comment]
Hi @bugraaydogar,

Awesome 🤩, I'll follow your instructions 🤞.

Many thanks

**Comment by jdbelo** [comment]
Thanks @bugraaydogar for your tips. Just a quick update, upgrading iot-entity image allow me to overcome the problem I was facing. The iot-agent is now able to connect to the mqtt broker 😃. Problem solved 💪

**Comment by jdbelo** [comment]
Hi @bugraaydogar,

I'm sorry for reopening this issue, but following your tips, I have found another issue that might be familiar to you and I'd like to request your help again. 

In order to run the most recent version of the services, I have rebuilt all the images (iot-identity, iot-management and iot-devicetwin) and pointed the .ymal file to the new images.

After re-deploying the services, everything seems to be running normally. However, I get an error message when I try to register my device on the iot-management portal ("RegDevice: sql: no rows in result set"). Also, probably because the device is not registered, I get an error message on the iot-agent log ("Error with MQTT connection: Network Error : %!s(<nil>)").

Have you ever faced a similar problem? Do you know how to overcome it?

One thing that came up to my mind that I might be doing wrong is cleaning the resources. In order to be able to run the `./deploy.sh <ip-or-domain-name>` again and to recreate the entire system, I have been removing the microk8s snap and then executing the deploy.sh file. Do you know if there is any other way? Or is this ok?

Many thanks

**Comment by bugraaydogar** [comment]
Hi @jdbelo,

I have seen issues regarding to the "Error with MQTT connection" and they were mainly because of the port forwarding. 
I don't know where you deploy but please make sure that you allowed MQTT port as part of your inbound network configuration. In addition to that, make sure to expose services outside of your Kubernetes cluster with port forwarding. E.g.

`kubectl port-forward your-mqtt-deployment --address 0.0.0.0 8883:8883`

For more details, I would suggest to download the whitepaper in below for better understanding and troubleshooting.
https://ubuntu.com/engage/iot-device-management-whitepaper

Cheers,
Bugra

**Comment by jdbelo** [comment]
Hi @bugraaydogar,

Once again thanks for all your tips.

I found the problem was related to cookies or browser cache. After clearing the cache and removing the cookies I have never had the "RegDevice: sql: no rows in result set" message anymore. 

On the device side, reinstalling the iot-agent allowed me to overcome the problem.

Cheers
